#change the biund mount location /home/ubuntu/authelia/config as desired
#place user_database.yml and configuration.yml at the bind mount location

#start authelia using
#<sudo> docker compose up

#stop/restart
#<sudo> docker compose down
#<sudo> docker compose restart

#ports - change this to port of choice


services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped

    ports:
      - "127.0.0.1:9091:9091"

    volumes:
      - /home/ubuntu/authelia/config:/config
